{


  parserClass="com.mwplugin.parser.MediaWikiParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="MediaWiki"
  psiImplClassSuffix="Impl"
  psiPackage="com.mwplugin.psi"
  psiImplPackage="com.mwplugin.psi.impl"

  elementTypeHolderClass="com.mwplugin.psi.MediaWikiTypes"
  elementTypeClass="com.mwplugin.psi.MediaWikiElementType"
  tokenTypeClass="com.mwplugin.psi.MediaWikiTokenType"

  psiImplUtilClass="com.mwplugin.psi.impl.MediaWikiPsiImplUtil"

    generate = [token-case="lower"]


    tokens = [
//        space='regexp:\s+'
//        comment='regexp://.*'
        quote5 = "'''''"
        quote3 = "'''"
        quote2 = "''"
        htmlcommentopen = "<!--"
        htmlcomentclose = "-->"
        openbracket = "["
        closebracket = "]"
        refopen = "<ref"
        refclose = "</ref>"
        newline='regexp:[\r\n]'
        lcaseletter='regexp:[a-z]'
        ucaseletter='regexp:[A-Z]'
        decimaldigit='regexp:\d'
        otherletter='regexp:[\p{L}]'
        equals5="====="
        equals4="===="
        equals3="==="
        equals2="=="
        unescapedampersand = "&"
        unescapedlessthan = "<"
        unescapedgreaterthan = ">"
        underscore = "_"
        space = " "
        doublequote = "regexp:\x22"
        TAB = "regexp:\t"
//        tablecellstart = "regexp:(?!\n)\p{Blank}*[\||\!]"
        equals = "="
        curlyopen2 = "{{"
        curlyclose2 = "}}"
        pipe = "|"

//        okaysymbols = "regexp:[\(|\)|_|\.|\!|\/|\-|\:|#]"
//        lcaseletter="regexp:\d"
    ]
}

root ::= text

html-unsafe-symbol ::=
	unescapedampersand|
	unescapedlessthan|
	unescapedgreaterthan

symbol ::=
	html-unsafe-symbol|
	underscore|
	"."|
	","|
	"("|")"|"-"|":"|"#"|"/"|"'"|";"|"|"|"–"|doublequote|"!"|"%"|"?"|"_"|"—"|"+"|"$"|"~"|"·"|"’"|equals|"†"

text ::= (!"|" (decimaldigit | symbol | lcaseletter | ucaseletter))* "|" "a"





